# -------------------------- #
# AutismChat 4            #
# Designed by Freyr LePage  #
# Programmed by Dev_Richard   #
# -------------------------- #
#
# The following template is for settings that players start with.
# If partyID is blank in the template, then a new partyID is generated for each new player.
templateForFirstLogin:
  partyID: 0
  defaultColor: WHITE
  globalChat: true
  displayMotd: true
#
# Players login/logoff messages are not displayed to red players
redhidesloginnotify: false
#
# If this setting is enabled it will display all the user's settings to them when they login
showLoginReport: true
#
status: 'defaultColor,globalChat,partyMembers'
loginReport: 'colourSetting,defaultColor,yellowList,othersYellowList,globalChat,partyMembers'
yellowListCommand: 'yellowList,othersYellowList'
